language: java

jdk:
  - openjdk8

os:
  - linux

script:
  - CF_ENDPOINT='api.run.pivotal.io'
  - CF_ORGANIZATION='FrameworksAndRuntimes'
  - CF_SPACE='rwinch'
  - ./gradlew check
after_success:
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" = "false" && $TRAVIS_BRANCH == 'master' && $TRAVIS_SECURE_ENV_VARS == 'true' ]] ; then
      ./ci/scripts/install-cf.sh
      export PATH=$PATH:$PWD
      cf login -a $CF_ENDPOINT -o $CF_ORGANIZATION -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD
      ./ci/scripts/cf-push.sh spring-release-notifications $SLACK_OAUTH_TOKEN $SLACK_CHANNEL_ID $GITHUB_SECRET $TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT
    fi

after_failure: cat $PWD/build/reports/tests/*/classes/*.html

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
