/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.spring.tools

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest
import org.springframework.boot.test.mock.mockito.MockBean

/**
 * @author Rob Winch
 */
@WebMvcTest
internal class MilestoneEventDeserializationTests {
    @Autowired
    lateinit var mapper: ObjectMapper

    @MockBean
    lateinit var slack: SlackService

    @Test
    @Disabled
    fun editedWhenDueDateNullToSet() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/3",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/3",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/3/labels",
    "id": 4864559,
    "node_id": "MDk6TWlsZXN0b25lNDg2NDU1OQ==",
    "number": 3,
    "title": "3",
    "description": "",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-20T23:12:54Z",
    "updated_at": "2019-11-21T03:10:06Z",
    "due_on": "2019-11-20T08:00:00Z",
    "closed_at": null
  },
  "changes": {

  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isFalse()
        assertThat(changes.dueOn.isChanged).isTrue()
    }

    @Test
    fun editedWhenDueDateSetToSet() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6",
    "description": "",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:23:26Z",
    "due_on": "2019-11-22T08:00:00Z",
    "closed_at": null
  },
  "changes": {
    "due_on": {
      "from": "2019-11-21T00:00:00.000Z"
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isFalse()
        assertThat(changes.dueOn.isChanged).isTrue()
    }

    @Test
    fun editedWhenDueDateSetToNull() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6",
    "description": "",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:24:50Z",
    "due_on": null,
    "closed_at": null
  },
  "changes": {
    "due_on": {
      "from": "2019-11-22T00:00:00.000Z"
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isFalse()
        assertThat(changes.dueOn.isChanged).isTrue()
    }

    @Test
    fun editedWhenTitleSetToSet() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6.1",
    "description": "",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:27:07Z",
    "due_on": null,
    "closed_at": null
  },
  "changes": {
    "title": {
      "from": "6"
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isTrue()
        assertThat(changes.description.isChanged).isFalse()
        assertThat(changes.dueOn.isChanged).isFalse()
    }

    @Test
    fun editedWhenDescriptionNullToSet() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6.1",
    "description": "description",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:28:52Z",
    "due_on": null,
    "closed_at": null
  },
  "changes": {
    "description": {
      "from": ""
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isTrue()
        assertThat(changes.dueOn.isChanged).isFalse()
    }

    @Test
    fun editedWhenDescriptionSetToSet() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6.1",
    "description": "description 2",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:29:39Z",
    "due_on": null,
    "closed_at": null
  },
  "changes": {
    "description": {
      "from": "description"
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isTrue()
        assertThat(changes.dueOn.isChanged).isFalse()
    }

    @Test
    fun editedWhenDescriptionSetToNull() {
        val milestoneEvent: MilestoneEvent  = mapper.readValue("""{
  "action": "edited",
  "milestone": {
    "url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6",
    "html_url": "https://github.com/rwinch/github-api-playground/milestone/6",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones/6/labels",
    "id": 4866865,
    "node_id": "MDk6TWlsZXN0b25lNDg2Njg2NQ==",
    "number": 6,
    "title": "6.1",
    "description": "",
    "creator": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 0,
    "state": "open",
    "created_at": "2019-11-21T14:22:08Z",
    "updated_at": "2019-11-21T14:31:19Z",
    "due_on": null,
    "closed_at": null
  },
  "changes": {
    "description": {
      "from": "description 2"
    }
  },
  "repository": {
    "id": 223033401,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjMwMzM0MDE=",
    "name": "github-api-playground",
    "full_name": "rwinch/github-api-playground",
    "private": false,
    "owner": {
      "login": "rwinch",
      "id": 362503,
      "node_id": "MDQ6VXNlcjM2MjUwMw==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rwinch",
      "html_url": "https://github.com/rwinch",
      "followers_url": "https://api.github.com/users/rwinch/followers",
      "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
      "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
      "organizations_url": "https://api.github.com/users/rwinch/orgs",
      "repos_url": "https://api.github.com/users/rwinch/repos",
      "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rwinch/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/rwinch/github-api-playground",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/rwinch/github-api-playground",
    "forks_url": "https://api.github.com/repos/rwinch/github-api-playground/forks",
    "keys_url": "https://api.github.com/repos/rwinch/github-api-playground/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rwinch/github-api-playground/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rwinch/github-api-playground/teams",
    "hooks_url": "https://api.github.com/repos/rwinch/github-api-playground/hooks",
    "issue_events_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rwinch/github-api-playground/events",
    "assignees_url": "https://api.github.com/repos/rwinch/github-api-playground/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rwinch/github-api-playground/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rwinch/github-api-playground/tags",
    "blobs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rwinch/github-api-playground/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rwinch/github-api-playground/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rwinch/github-api-playground/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rwinch/github-api-playground/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rwinch/github-api-playground/languages",
    "stargazers_url": "https://api.github.com/repos/rwinch/github-api-playground/stargazers",
    "contributors_url": "https://api.github.com/repos/rwinch/github-api-playground/contributors",
    "subscribers_url": "https://api.github.com/repos/rwinch/github-api-playground/subscribers",
    "subscription_url": "https://api.github.com/repos/rwinch/github-api-playground/subscription",
    "commits_url": "https://api.github.com/repos/rwinch/github-api-playground/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rwinch/github-api-playground/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rwinch/github-api-playground/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rwinch/github-api-playground/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rwinch/github-api-playground/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rwinch/github-api-playground/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rwinch/github-api-playground/merges",
    "archive_url": "https://api.github.com/repos/rwinch/github-api-playground/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rwinch/github-api-playground/downloads",
    "issues_url": "https://api.github.com/repos/rwinch/github-api-playground/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rwinch/github-api-playground/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rwinch/github-api-playground/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rwinch/github-api-playground/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rwinch/github-api-playground/labels{/name}",
    "releases_url": "https://api.github.com/repos/rwinch/github-api-playground/releases{/id}",
    "deployments_url": "https://api.github.com/repos/rwinch/github-api-playground/deployments",
    "created_at": "2019-11-20T21:45:51Z",
    "updated_at": "2019-11-20T23:24:16Z",
    "pushed_at": "2019-11-20T21:45:52Z",
    "git_url": "git://github.com/rwinch/github-api-playground.git",
    "ssh_url": "git@github.com:rwinch/github-api-playground.git",
    "clone_url": "https://github.com/rwinch/github-api-playground.git",
    "svn_url": "https://github.com/rwinch/github-api-playground",
    "homepage": null,
    "size": 0,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  "sender": {
    "login": "rwinch",
    "id": 362503,
    "node_id": "MDQ6VXNlcjM2MjUwMw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/362503?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rwinch",
    "html_url": "https://github.com/rwinch",
    "followers_url": "https://api.github.com/users/rwinch/followers",
    "following_url": "https://api.github.com/users/rwinch/following{/other_user}",
    "gists_url": "https://api.github.com/users/rwinch/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rwinch/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rwinch/subscriptions",
    "organizations_url": "https://api.github.com/users/rwinch/orgs",
    "repos_url": "https://api.github.com/users/rwinch/repos",
    "events_url": "https://api.github.com/users/rwinch/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rwinch/received_events",
    "type": "User",
    "site_admin": false
  }
}""")

        val changes = milestoneEvent.changes!!
        assertThat(changes.title.isChanged).isFalse()
        assertThat(changes.description.isChanged).isTrue()
        assertThat(changes.dueOn.isChanged).isFalse()
    }
}